### ISSUE TITLE
[FR]: Default style property in `useSx` option

### ISSUE THREAD

**Issue by mym0404** [mj-studio-library/react-native-styled-system#39]
### Describe the problem

At now, the `getStyle` function takes `SxProps` as a parameter for passing additional style properties.

It is handled with lowest priority because it is used for **default property** sometimes.

We should separate a concern between defining default style properties and passing additional style properties.

## Step 1. Create `default(not fixed name)` options to `useSx` hook.

```tsx
const { /* ... */ } = useSx(props, {
  default: {
    borderWidth: 1,
  },
});
```

> [!IMPORTANT]
> This `SxProps` should be handled as **most lowest priority**

## Step 2(NEED DISCUSSION). The priority of `SxProps` as `getStyle` parameter should be highest one?(lower than `style`).

I have no idea how this priority should be updated.

> [!NOTE]
> We should update this new behaviors in the docs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
@zmin9 need discussion

**Comment by zmin9** [comment]
I think `SxProps` passed to `getStyle` should have the highest priority.
Given the usage(_passing style prop to component → useSx → getStyle_), it makes sense that they would be applied last.

**Comment by mym0404** [comment]
> I think `SxProps` passed to `getStyle` should have the highest priority. Given the usage(_passing style prop to component → useSx → getStyle_), it makes sense that they would be applied last.

I think the priority of the `useSx-default` properties should be lower than _passing style prop to component_. Because if the priority of `default` is higher than it, there is no way to overwrite `default` properties declared in component.

**Comment by zmin9** [comment]
> > I think `SxProps` passed to `getStyle` should have the highest priority. Given the usage(_passing style prop to component → useSx → getStyle_), it makes sense that they would be applied last.
> 
> I think the priority of the `useSx-default` properties should be lower than _passing style prop to component_. Because if the priority of `default` is higher than it, there is no way to overwrite `default` properties declared in component.

oh I agree on lowest priority of `useSx-default` prop.
It is shortcut to set default style without thinking about the priority between `style`, `sx`, `SxProps`. So convenient!
```ts 
// without default props
useSx({
  style: {
     borderWidth: 1, // it overwrite component sxProps although it is default style
     ...props?.style,
  },
  /* ... */
   ...props,
})
```
-------------------------------
To be clear, it would be good that  the `default` of `useSx` had the lowest priority and `SxProps` of `getStyle` had the highest priority.

**Comment by mym0404** [comment]
Right, let's do like this.

**Comment by mym0404** [comment]
@zmin9 Can you name default properties as `fallback`? I think it is more meaningful than `default`.

**Comment by zmin9** [comment]
@mym0404 
While resolving this issue, I'd like to discuss: do we really need `sxProps` for `getStyle`?
I don't think we will use it often, and if we do, it could be written like this:
```jsx
<View style={[getStyle(), { backgroundColor: 'red }]} />
```
Also, I think the priority with `transform` is confusing.

**Comment by mym0404** [comment]
I agree with that. Did you read the updated docs for this?

**Comment by mym0404** [comment]
If passing plain old style into `style` will be a alternative or recommended way of this package, then the main benefit of this package(easing of styling in various theme) would be broken.

I am curious about `sx` parameter of `getStyle` is really required in any aspect of usages.

**Comment by zmin9** [comment]
If we need to use the state value of some child component, as in the example below, `getStyle-sxProps` would be needed :sweat_smile: . Though this case is not common, it is difficult to be covered with `fallback` or `transform`.

Or why not just have `useSx` return the `getThemedStyle(sx?:SxProps)` function?
I think it would be confusing to use `getStyle(sx?: SxProps)` with priority.
```jsx
<View style={[getThemedStyle({mt: 2}), getStyle(), getThemedStyle({mb: 4})]} />
```

**Comment by zmin9** [comment]
+)
And then, I read [this docs](https://mj-studio-library.github.io/react-native-styled-system/docs/usage/style-parsing), do you think this `getStyle-sxProps` should have higher priority than `transform`?
I naturally assumed that the getStyle would be affected by `transform` because it is the return value of `useSx` with `transform` property.

**Comment by mym0404** [comment]
From this discussion, it was more clear that `getStyle-sx` is so confusing.

I think we have to remove it.(with introducing `fallback`).  

In your reply, `getThemedStyle` is a good catch.

How about this?

Create a new hook `useThemedStyle` or `useSxStyle`

```tsx
const getThemedStyle = useThemedStyle();

return <View style={getThemedStyle({ mt: 2, /* ... */ })}/>
``` 

> [!NOTE]
> I insist that `useSx` shouldn't have two or more usage other than `props` -> `style`.
> If we create a new hook for the pure `nothing` -> `style` usage, `useSx` hook is separated from the other usage.
